# Generated by Django 5.1.6 on 2025-02-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest", "0003_entity_user_entity_unique_entity_per_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="value",
            name="boolean_value",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="value",
            name="date_value",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="value",
            name="float_value",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="value",
            name="integer_value",
            field=models.IntegerField(null=True),
        ),
    ]
